update:修改J2Chache从application.properties文件读配置,不从默认配置文件读
nutzam/nutzboot pull request #117
Opened 2018-01-28 02:10 UTC by TopCoderMyDream

2018-01-28 02:36 UTC, wendal commented on nutzboot-starter/nutzboot-starter-j2cache/src/main/java/org/nutz/boot/starter/j2cache/J2cacheStarter.java
> +            J2CacheConfig j2CacheConfig = J2CacheConfig.initFromConfig("/application.properties");
其实呢... 不能直接调用initFromConfig的(XXX: 竟然只能传入路径)

需要从conf对象构建Properties的, 例如

```
@Inject
PropertiesProxy conf;

public CacheChannel getCacheChannel()  {
          J2CacheConfig j2CacheConfig = new J2CacheConfig ();
          j2CacheConfig.setSerialization(conf.getProperty("j2cache.serialization", "fst"));
          set broadcast... and Properties
          set l1CacheName ... and Properties
          set l2CacheName and Properties

}
```

2018-01-28 02:36 UTC, wendal submitted a review, later dismissed

2018-01-28 02:38 UTC, wendal requested changes
直接从application.properties读取,这方式太硬了

2018-01-28 02:41 UTC, wendal commented on nutzboot-starter/nutzboot-starter-j2cache/src/main/java/org/nutz/boot/starter/j2cache/J2cacheStarter.java
> +            J2CacheConfig j2CacheConfig = J2CacheConfig.initFromConfig("/application.properties");
```java
String PRE = "j2cache.";
Properties broadcastProperties  = new Properties();
Properties l1CacheNameProperties  = new Properties();
Properties l2CacheNameProperties  = new Properties();
conf.keys().forEach((key) -> {
             if (key.startsWith(PRE  + broadcast + ".") {
                      broadcastProperties.put(key.subString(PRE.length()), conf.get(key);)
             }
             l1CacheNameProperties 和  l2CacheNameProperties   是同理
});
```

2018-01-28 05:20 UTC, TopCoderMyDream commented
其实j2cache的代码也是读取的对应开头的配置,为何要手动再写?
` public final static J2CacheConfig initFromConfig(String configResource) throws IOException {
        J2CacheConfig config = new J2CacheConfig();
        try (InputStream stream = getConfigStream(configResource)){
            config.properties = new Properties();
            config.properties.load(stream);
            config.serialization = config.properties.getProperty("j2cache.serialization");
            config.broadcast = config.properties.getProperty("j2cache.broadcast");
            config.l1CacheName = config.properties.getProperty("j2cache.L1.provider_class");
            config.l2CacheName = config.properties.getProperty("j2cache.L2.provider_class");
            config.properties.forEach((k,v) -> {
                String key = (String)k;
                if(key.startsWith(config.broadcast + "."))
                    config.broadcastProperties.setProperty(key.substring((config.broadcast + ".").length()), (String)v);
                if(key.startsWith(config.l1CacheName + "."))
                    config.l1CacheProperties.setProperty(key.substring((config.l1CacheName + ".").length()), (String)v);
                if(key.startsWith(config.l2CacheName + "."))
                    config.l2CacheProperties.setProperty(key.substring((config.l2CacheName + ".").length()), (String)v);

            });
        }
        return config;
    }
`

2018-01-28 05:23 UTC, TopCoderMyDream commented
j2cache的initFromConfig方法里也是读取的对应开头的配置,为何我们要再读出来?
`public final static J2CacheConfig initFromConfig(String configResource) throws IOException {
        J2CacheConfig config = new J2CacheConfig();
        try (InputStream stream = getConfigStream(configResource)){
            config.properties = new Properties();
            config.properties.load(stream);
            config.serialization = config.properties.getProperty("j2cache.serialization");
            config.broadcast = config.properties.getProperty("j2cache.broadcast");
            config.l1CacheName = config.properties.getProperty("j2cache.L1.provider_class");
            config.l2CacheName = config.properties.getProperty("j2cache.L2.provider_class");
            config.properties.forEach((k,v) -> {
                String key = (String)k;
                if(key.startsWith(config.broadcast + "."))
                    config.broadcastProperties.setProperty(key.substring((config.broadcast + ".").length()), (String)v);
                if(key.startsWith(config.l1CacheName + "."))
                    config.l1CacheProperties.setProperty(key.substring((config.l1CacheName + ".").length()), (String)v);
                if(key.startsWith(config.l2CacheName + "."))
                    config.l2CacheProperties.setProperty(key.substring((config.l2CacheName + ".").length()), (String)v);
            });
        }
        return config;
    }`

2018-01-28 05:25 UTC, TopCoderMyDream commented
大叔的意思是它读不到application.properties???还是出于什么考虑不然他读?

2018-01-28 05:46 UTC, wendal commented
因为不能假设applicatipn.properties存在哦，配置信息只能从conf对象获取，例如配置中心提供配置信息，本地根本没有applicatipn.properties

2018-01-28 06:19 UTC, TopCoderMyDream commented
还能这么玩....配置中心我都没玩过呢..腻害腻害我改一下

2018-01-28 09:02 UTC, wendal commented
应该是j2cache.jgroup.xxxx=xxx 的形式，所以要下面这样

broadcastProperties.put(key.subString(PRE.length() + broadcast.length() + 2), conf.get(key);)

2018-01-28 11:30 UTC, TopCoderMyDream commented
大叔我这思路对嘛....反射搞出来J2CacheConfig的对象

`       Properties nb_broadcastProperties = new Properties();
        Properties nb_l1CacheProperties = new Properties();
        Properties nb_l2CacheProperties = new Properties();
        String nb_serialization= Strings.trim(conf.get(PRE+"j2cache.serialization"));
        String nb_broadcast = Strings.trim(conf.get(PRE+"j2cache.broadcast"));
        String nb_l1CacheName = Strings.trim(conf.get(PRE+"j2cache.L1.provider_class"));
        String nb_l2CacheName = Strings.trim(conf.get(PRE+"j2cache.L2.provider_class"));
        conf.keys().forEach((k) -> {
            System.out.println(k.startsWith(nb_broadcast + "."));
            System.out.println("k:"+k);
            System.out.println(nb_broadcast + ".");
            if(k.startsWith(nb_broadcast + ".")) {
                nb_broadcastProperties.setProperty(k.substring(PRE.length()+(nb_broadcast + ".").length()), conf.get(k));
            }
            if(k.startsWith(nb_l1CacheName + "."))
                nb_l1CacheProperties.setProperty(k.substring(PRE.length()+(nb_l1CacheName + ".").length()),conf.get(k));
            if(k.startsWith(nb_l2CacheName + "."))
                nb_l2CacheProperties.setProperty(k.substring(PRE.length()+(nb_l2CacheName + ".").length()), conf.get(k));
        });
        J2CacheConfig j2CacheConfig = new J2CacheConfig();
        Mirror<J2CacheConfig> me = Mirror.me(j2CacheConfig);
        me.invoke(j2CacheConfig,"setBroadcast",nb_broadcast);
        me.invoke(j2CacheConfig,"setL1CacheName",nb_l1CacheName);
        me.invoke(j2CacheConfig,"setL2CacheName",nb_l2CacheName);
        me.invoke(j2CacheConfig,"setSerialization",nb_serialization);
        me.invoke(j2CacheConfig,"setBroadcastProperties",nb_broadcastProperties);
        me.invoke(j2CacheConfig,"setL1CacheProperties",nb_l1CacheProperties);
        me.invoke(j2CacheConfig,"setL2CacheProperties",nb_l2CacheProperties);
        return J2CacheBuilder.init(j2CacheConfig).getChannel();
`

2018-01-28 11:30 UTC, TopCoderMyDream commented
为啥github的插入代码那么难用?

2018-01-28 11:31 UTC, wendal commented
不需要反射吧？ 又不是private的构造方法

2018-01-28 11:36 UTC, wendal commented
那些setter方法都是public的啊。。。

2018-01-28 12:05 UTC, TopCoderMyDream commented
哈哈,搞懵逼了...

2018-01-28 13:08 UTC, wendal commented
我稍微改了一下你的代码

配置文件应该全部由j2cache.开头, 跟原版j2cache.properties有点区别, 这样也方便写@PropDoc

```properties
#J2Cache configuration


#########################################
# Cache Broadcast Method
# values:
# jgroups -> use jgroups's multicast
# redis -> use redis publish/subscribe mechanism
# xx.xxxx.xxxx.Xxxxx your own cache broadcast policy classname that implement net.oschina.j2cache.ClusterPolicy
#########################################

j2cache.broadcast = redis

#组播的通道名称
j2cache.jgroups.channel.name = j2cache
j2cache.jgroups.configXml = /network.xml

#########################################
# Level 1&2 provider
# values:
# none -> disable this level cache
# ehcache -> use ehcache2 as level 1 cache
# ehcache3 -> use ehcache3 as level 1 cache
# caffeine -> use caffeine as level 1 cache(only in memory)
# redis -> use redis(hashs) as level 2 cache
# [classname] -> use custom provider
#########################################

j2cache.L1.provider_class = caffeine
j2cache.L2.provider_class = redis

#########################################
# Cache Serialization Provider
# values:
# fst -> fast-serialization
# kyro -> kyro
# java -> java standard
# [classname implements Serializer]
#########################################

j2cache.serialization = fst

#########################################
# Ehcache configuration
#########################################

j2cache.ehcache.configXml = /ehcache.xml

j2cache.ehcache3.configXml = /ehcache3.xml
j2cache.ehcache3.defaultHeapSize = 1000

#########################################
# Caffeine configuration
# caffeine.region.[name] = size, xxxx[s|m|h|d]
#
#########################################

j2cache.caffeine.region.default = 1000, 1h 

#########################################
# Redis connection configuration
#########################################

#########################################
# Redis Cluster Mode
#
# single -> single redis server
# sentinel -> master-slaves servers
# cluster -> cluster servers (数据库配置无效，使用 database = 0）
# sharded -> sharded servers  (密码、数据库必须在 hosts 中指定，且连接池配置无效 ; redis://user:password@127.0.0.1:6379/0）
#
#########################################

j2cache.redis.mode = single

#redis storage mode (generic|hash)
j2cache.redis.storage = generic

## redis pub/sub channel name
j2cache.redis.channel = j2cache
## redis pub/sub server (using redis.hosts when empty)
j2cache.redis.channel.host =
j2cache.redis.channel.timeout = 1000

#cluster name just for sharded
j2cache.redis.cluster_name = j2cache

## redis cache namespace optional, default[j2cache]
j2cache.redis.namespace =

## connection
j2cache.redis.hosts = 127.0.0.1:6379
j2cache.redis.timeout = 2000
j2cache.redis.password =
j2cache.redis.database = 0

## redis pool properties
j2cache.redis.maxTotal = -1
j2cache.redis.maxIdle = 100
j2cache.redis.maxWaitMillis = 100
j2cache.redis.minEvictableIdleTimeMillis = 864000000
j2cache.redis.minIdle = 10
j2cache.redis.numTestsPerEvictionRun = 10
j2cache.redis.lifo = false
j2cache.redis.softMinEvictableIdleTimeMillis = 10
j2cache.redis.testOnBorrow = true
j2cache.redis.testOnReturn = false
j2cache.redis.testWhileIdle = false
j2cache.redis.timeBetweenEvictionRunsMillis = 300000
j2cache.redis.blockWhenExhausted = true
```

2018-01-29 05:53 UTC, wendal commented
有空的时候把它改完哦

2018-01-29 08:40 UTC, TopCoderMyDream commented
好的好的,我这边再调试一下就好

2018-01-29 17:55 UTC, zozoh commented
@TopCoderMyDream 蛋蛋加油

2018-01-30 02:53 UTC, TopCoderMyDream commented
就是因为空格才读不到文件的.....我直接从它原来配置文件复制的,每一项的值前面都有个空格....= =||

2018-01-30 03:44 UTC, wendal approved these changes

2018-01-30 03:45 UTC, merged

2018-02-03 12:44 UTC, wendal commented
我发现分支错了

2018-02-03 12:53 UTC, wendal commented
已合并到dev