添加nutzboot-starter-sqlxmltpl
nutzam/nutzboot pull request #158
Opened 2019-04-03 09:33 UTC by threefish

2019-04-03 12:11 UTC, wendal requested changes

2019-04-03 12:11 UTC, wendal commented on nutzboot-starter/nutzboot-starter-sqlxmltpl/pom.xml
> +		<version>2.3-SNAPSHOT</version>
版本号错了

2019-04-03 12:11 UTC, wendal commented on nutzboot-starter/nutzboot-starter-sqlxmltpl/src/main/java/org/nutz/boot/starter/sqlxmltpl/SqlXmlTplIocLoaderStarter.java
> +    protected static final String PRE = "SqlXmlTpl.";
确定要用这个前缀吗? 通常是小写

2019-04-03 12:12 UTC, wendal commented
nutzboot-starter的pom.xml需要引用它哦
根目录的README加上它哦
需要一起提交其demo哦

2019-04-04 07:14 UTC, threefish commented
@wendal pull 了最新的dev分支，按照要求修改了

2019-04-04 07:40 UTC, wendal commented on pom.xml
> +		<module>nutzboot-demo</module>
这个不要加啊, demo是profile里面添加的

2019-04-04 07:41 UTC, threefish commented on pom.xml
> +		<module>nutzboot-demo</module>
ok

2019-04-04 08:04 UTC, wendal approved these changes

2019-04-04 08:16 UTC, merged